name: 'Load Container Action'

description: 'Imports the image build caches and loads them for Docker CLI'

inputs:
  osg_series:
    description: 'OSG release series used to install packages'
    required: true
  repo:
    description: 'Input string that gets passed along to the docker build args'
    required: true
  context:
    description: 'Path to container files, including Dockerfile'
    required: false
    default: '.'
  timestamp_tag:
    description: >-
      Timestamped tag name (e.g.,
      "opensciencegrid/osgvo-docker-pilot3.6-release-YYYYMMDD-hhmm")
      used to pass the Dockerfile as $TIMESTAMP_TAG
    required: false
    default: ''
  cache:
    description: 'Generate a cache per image'
    required: false
    default: true

outputs:
  image_tag:
    description: 'The image tag available through Docker CLI tools'
    value: ${{ steps.generate-image-name.outputs.image }}:latest

runs:
  using: "composite"
  steps:
  - uses: actions/checkout@v2

  - id: generate-image-name
    shell: bash
    run: |
      if [[ ${{ inputs.context }} == "." ]] || \
         [[ ${{ inputs.context }} == "./" ]]; then
         # Try to guess the image name from our docker repo naming conventions
         # E.g., opensciencegrid/docker-frontier-squid
         IMAGE_NAME=${GITHUB_REPOSITORY/opensciencegrid\/docker-//}
      elif [[ -d ${{ inputs.context }} ]]; then
         # Assume that the containing dir is the image name
         IMAGE_NAME=$(basename ${{ inputs.context }})
      else
        echo "${{ inputs.context }} is not a directory"
        exit 1
      fi
      echo "::set-output name=image::$IMAGE_NAME"
  
  - id: generate-cache-file
  shell: bash
  run: |
    if [[ ${{ inputs.cache }} == true ]]; then
      CACHE_FILE="/tmp/.buildx-cache"
    else
      CACHE_FILE="/tmp/throwaway"
    fi
    echo "::set-output name=cachefile::$CACHE_FILE"

  - name: Import Docker images from cache
    uses: actions/cache@v2
    with:
      path: ${{ steps.generate-cache-file.outputs.cachefile }}
      key: ${{ steps.generate-image-name.outputs.image }}_${{ inputs.osg_series}}-${{ inputs.repo }}-buildx-${{ github.sha }}-${{ github.run_id }}
      restore-keys: |
        ${{ steps.generate-image-name.outputs.image }}-${{ inputs.osg_series }}-
        ${{ steps.generate-image-name.outputs.image }}-

  - name: Set up Docker Buildx
    uses: docker/setup-buildx-action@v1

  - name: Load Docker images for use in Docker CLI
    uses: docker/build-push-action@v2.2.2
    with:
      push: False
      context: .
      build-args: |
        BASE_YUM_REPO=${{ inputs.repo }}
        BASE_OSG_SERIES=${{ inputs.osg_series }}
        TIMESTAMP_TAG=${{ inputs.timestamp_tag }}
      load: True # allow acces to built images through the Docker CLI
      tags: ${{ steps.generate-image-name.outputs.image }}:latest
      cache-from: type=local,src=${{ steps.generate-cache-file.outputs.cachefile }}

