name: 'Load Container Action'

description: 'Imports the image build caches and loads them for Docker CLI'

inputs:
  osg_series:
    description: 'OSG release series used to install packages'
    required: true
  repo:
    description: 'Input string that gets passed along to the docker build args'
    required: true
  context:
    description: 'Path to container files, including Dockerfile'
    required: false
    default: '.'
  timestamp_tag:
    description: >-
      Timestamped tag name (e.g.,
      "opensciencegrid/osgvo-docker-pilot3.6-release-YYYYMMDD-hhmm")
      used to pass the Dockerfile as $TIMESTAMP_TAG
    required: false
    default: ''
  image_name:
    description: 'Name of the image to build, e.g. "opensciencegrid/software-base"'
    required: false
    default: ''
    
outputs:
  image_tag:
    description: 'The image tag available through Docker CLI tools'
    value: ${{ steps.generate-image-name.outputs.image }}:latest

runs:
  using: "composite"
  steps:
  - uses: actions/checkout@v3

  - id: generate-image-name
    shell: bash
    run: |
      if [[ -n "${{ inputs.image_name }}" ]]; then
          IMAGE_NAME="${{ inputs.image_name }}"
      elif [[ ${{ inputs.context }} == "." ]] || \
         [[ ${{ inputs.context }} == "./" ]]; then
         # Try to guess the image name from our docker repo naming conventions
         # E.g., opensciencegrid/docker-frontier-squid
         IMAGE_NAME=${GITHUB_REPOSITORY/opensciencegrid\/docker-//,,}
      elif [[ -d ${{ inputs.context }} ]]; then
         # Assume that the containing dir is the image name
         IMAGE_NAME=$(basename ${{ inputs.context }})
      else
        echo "No image_name provided and ${{ inputs.context }} is not a directory"
        exit 1
      fi
      echo "image=${IMAGE_NAME,,}" >> $GITHUB_OUTPUT

  - name: Import Docker images from cache
    uses: actions/cache@v3
    with:
      path: /tmp/.buildx-cache
      key: ${{ steps.generate-image-name.outputs.image }}_${{ inputs.osg_series}}-${{ inputs.repo }}-buildx-${{ github.sha }}-${{ github.run_id }}

  - name: Set up Docker Buildx
    uses: docker/setup-buildx-action@v2.2.0

  - name: Load Docker images for use in Docker CLI
    uses: docker/build-push-action@v4
    with:
      push: False
      context: .
      build-args: |
        BASE_YUM_REPO=${{ inputs.repo }}
        BASE_OSG_SERIES=${{ inputs.osg_series }}
        TIMESTAMP_TAG=${{ inputs.timestamp_tag }}
      load: True # allow acces to built images through the Docker CLI
      tags: ${{ steps.generate-image-name.outputs.image }}:latest
      cache-from: type=local,src=/tmp/.buildx-cache

